name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter build web --release
        working-directory: ./
      # base-href "/${{ github.event.repository.name }}/"
      - run: |
          # 2. change path to [existed lib/main.dart path]/build/web
          cd ./build/web
          ls
          git init
          git config --global user.email ninebell94@gmail.com
          git config --global user.name Ninebell
          git status
          git remote add origin https://$@github.com/Ninebell/ninebell.github.io.git 
          git checkout -b gh-pages
          git add --all
          echo commit
          git commit -m "update"
          echo push
          git push --set-upstream origin gh-pages -f
