name: Build and deploy flutter web app

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter build web --base-href "/${{ github.event.repository.name }}/"
      - run: |
          # 2. change path to [existed lib/main.dart path]/build/web
          cd ./build/web
          git init
          git config --global user.name Ninebell
          git config --global user.email ninebell94@gmail.com
          git remote add origin https://$@github.com/Ninebell/ninebell.github.io.git 
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
